### ISSUE TITLE
feature request: replacement for labelCompare

### ISSUE THREAD

**Issue by furlongm** [ihiji/version_utils#10]
I've been trying version_utils to see if I can use it as a replacement for labelCompare from rpm-python (which is not available on pypi). There seems to be some differences in the output:

Compare version_utils output:

```
apparmor-abstractions-2.10.1-5.1-noarch -> apparmor-abstractions-2.10-3.2-noarch (Bugfix)
apparmor-docs-2.10.1-5.1-noarch -> apparmor-docs-2.10-3.2-noarch (Bugfix)
apparmor-parser-2.10.1-5.1-x86_64 -> apparmor-parser-2.10-3.2-x86_64 (Bugfix)
apparmor-profiles-2.10.1-5.1-noarch -> apparmor-profiles-2.10-3.2-noarch (Bugfix)
apparmor-utils-2.10.1-5.1-noarch -> apparmor-utils-2.10-3.2-noarch (Bugfix)
bpython-0.12-14.7-noarch -> bpython-0.14.2-26.3-noarch (Bugfix)
deltarpm-3.6.1-7.1-x86_64 -> deltarpm-3.6-5.1-x86_64 (Bugfix)
libapparmor1-2.10.1-5.1-x86_64 -> libapparmor1-2.10-3.2-x86_64 (Bugfix)
libical1-1.0.1-11.1-x86_64 -> libical1-1.0-9.7-x86_64 (Bugfix)
perl-apparmor-2.10.1-5.1-x86_64 -> perl-apparmor-2.10-3.2-x86_64 (Bugfix)
python3-apparmor-2.10.1-5.1-x86_64 -> python3-apparmor-2.10-3.2-x86_64 (Bugfix)
yast2-users-3.1.41.3-10.1-x86_64 -> yast2-users-3.1.41-4.1-x86_64 (Bugfix)
```

vs labelCompare output:

```
bpython-0.12-14.7-noarch -> bpython-0.14.2-26.3-noarch (Bugfix)
```

The labelCompare output is correct as far as the system is concerned.

Shouldn't both of the following functions return the same value?

```
>>> compare_packages('apparmor-abstractions-2.10.1-5.1-noarch', 'apparmor-abstractions-2.10-3.2-noarch')
1
>>> compare_versions('2.10.1-5.1', '2.10-3.2')
-1
```

Also related, would a drop-in replacement for labelCompare be a possibility?

**Comment by mplanchard** [comment]
That's interesting. It should, in theory, return the same values, and in fact `compare_packages` calls `compare_versions` to get its results. My initial suspicion is that it's a parsing issue, since `compare_packages` attempts to split out any provided epoch value, the version string, and the release string prior to calling `compare_versions`.

I can't look into this in depth during the day, but I'll spend some time this evening using your examples to figure out where the parsing algorithm is going awry.

Ultimately, I think we should provide the same functionality as labelCompare, although I haven't explicitly developed against it as a reference, so some additions or changes may need to be made for it to be a drop in replacement. It's a good goal, and one that I'm willing to work towards.

**Comment by mplanchard** [comment]
Just another quick note - one of the reasons the parser seems to be getting confused is that it expects the architecture string to be separated by a `'.'` from the rest of the string, which seems to have been the standard output of something like `rpm -q <package>` on RHEL 6 and above. What is the source of your package version outputs, so I can look into adding support for that format?

**Comment by furlongm** [comment]
Oops, I am the source of the `-` instead of the `.`. See https://github.com/furlongm/patchman/blob/master/patchman/repos/models.py

However, I just used the output of get_version_string_deb for testing purposes. If I change it to a dot instead of a dash, I still get the same results as above.

**Comment by furlongm** [comment]
>>> compare_packages('apparmor-abstractions-2.10.1-5.1.noarch', 'apparmor-abstractions-2.10-3.2.noarch')
1
>>> compare_versions('2.10.1-5.1', '2.10-3.2')
-1

**Comment by furlongm** [comment]
So changing the dash `'-'` to a dot `'.'` makes no difference:

```
>>> compare_packages('apparmor-abstractions-2.10.1-5.1.noarch', 'apparmor-abstractions-2.10-3.2.noarch')
1
>>> compare_versions('2.10.1-5.1', '2.10-3.2')
-1
```

and with labelCompare:

```
>>> labelCompare(('2', '10.1', '5.1'), ('2', '10-3', '2'))
-1
```

so the compare_versions output seems to be correct, and the compare_packages output is not.

We can confirm this by passing `arch_provided=False`:

```
>>> compare_packages('apparmor-abstractions-2.10.1-5.1', 'apparmor-abstractions-2.10-3.2', arch_provided=False)
1
```

So the following works, but it's not what compare_packages does unfortunately:

```
>>> compare_versions('2.10.1-5.1', '2.10-3.2')
-1
```

This is actually what compare_packages does, and this is where it fails:

```
>>> compare_versions('10.1', '10')
1
```

**Comment by mplanchard** [comment]
Again, sorry for the delay here; we had some unexpected loss of resources at work, and I've been pulling more time than usual. I'll have a new release out before the end of the week.

**Comment by mplanchard** [comment]
So, the reason for the `compare_versions` issue that you're seeing is that `compare_versions`, as it stands, is not designed to parse version strings that include releases (the section after the dash). In the documentation for the parameters, they specify "an RPM version **or** release string" (emphasis mine). Comparing the versions alone shows the correct output, as you have demonstrated, in which `10.1` is considered to be newer than `10`.

I'm not inclined to change the intended functionality of `compare_versions`, but I'd be happy to add a function that can compare a version string with the associated release string, if that's something you'd be interested in. Let me know!

I'm going to start looking into the bpython example here in a moment. Could you clarify the difference between the outputs? In your initial post, you said the version_utils output is:

```
bpython-0.12-14.7-noarch -> bpython-0.14.2-26.3-noarch (Bugfix)
```

and the labelCompare output is:

```
bpython-0.12-14.7-noarch -> bpython-0.14.2-26.3-noarch (Bugfix)
```

but those look the same to me.

**Comment by mplanchard** [comment]
In the case of bpython, I get the following (debug output turned on):

``` python
n[16]: rpm.compare_packages('bpython-0.12-14.7-noarch', 'bpython-0.14.2-26.3-noarch')
resolve_versions(bpython-0.12-14.7-noarch, bpython-0.14.2-26.3-noarch)
parse_information(bpython-0.12-14.7-noarch, True)
_pop_arch['b', 'p', 'y', 't', 'h', 'o', 'n', '-', '0', '.', '1', '2', '-', '1', '4', '.', '7', '-', 'n', 'o', 'a', 'r', 'c', 'h']
arch chars: ['7', '-', 'n', 'o', 'a', 'r', 'c', 'h']
updated version_string: bpython-0.12-14
parsed information: {'name': 'bpython', 'EVR': ('0', '0.12', '14'), 'arch': '7-noarch'}
parse_information(bpython-0.14.2-26.3-noarch, True)
_pop_arch['b', 'p', 'y', 't', 'h', 'o', 'n', '-', '0', '.', '1', '4', '.', '2', '-', '2', '6', '.', '3', '-', 'n', 'o', 'a', 'r', 'c', 'h']
arch chars: ['3', '-', 'n', 'o', 'a', 'r', 'c', 'h']
updated version_string: bpython-0.14.2-26
parsed information: {'name': 'bpython', 'EVR': ('0', '0.14.2', '26'), 'arch': '3-noarch'}
compare_versions(0.12, 0.14.2)
starting loop comparing ['0', '.', '1', '2'] to ['0', '.', '1', '4', '.', '2']
_check_leading(['0', '.', '1', '2'], ['0', '.', '1', '4', '.', '2'])
updated list: ['0', '.', '1', '2']
updated list: ['0', '.', '1', '4', '.', '2']
_get_block_result(['0', '.', '1', '2'], ['0', '.', '1', '4', '.', '2'])
_pop_digits(['0', '.', '1', '2'])
got digits: ['0']
updated char list: ['.', '1', '2']
_pop_digits(['0', '.', '1', '4', '.', '2'])
got digits: ['0']
updated char list: ['.', '1', '4', '.', '2']
_compare_blocks(['0'], ['0'])
_trim_zeros((['0'], ['0']))
updated block: []
updated block: []
blocks are equal
starting loop comparing ['.', '1', '2'] to ['.', '1', '4', '.', '2']
_check_leading(['.', '1', '2'], ['.', '1', '4', '.', '2'])
updated list: ['1', '2']
updated list: ['1', '4', '.', '2']
_get_block_result(['1', '2'], ['1', '4', '.', '2'])
_pop_digits(['1', '2'])
got digits: ['1', '2']
updated char list: []
_pop_digits(['1', '4', '.', '2'])
got digits: ['1', '4']
updated char list: ['.', '2']
_compare_blocks(['1', '2'], ['1', '4'])
_trim_zeros((['1', '2'], ['1', '4']))
updated block: ['1', '2']
updated block: ['1', '4']
blocks are not equal
Out[16]: -1
```

Which seems correct to me (0.14.2 is newer than 0.12).

**Comment by furlongm** [comment]
There are no issues with the bpython comparison, that one was correct. As noted in the initial report, labelCompare from python-rpm correctly identifies bpython as the only upgrade available.

**Comment by furlongm** [comment]
I've stopped using compare_versions directly, as I was using it incorrectly.

I misunderstood that it would compare full rpm version strings (EVR), similar to labelCompare. So maybe I could leave this issue open as a feature request for a drop-in replacement for labelCompare?

**Comment by mplanchard** [comment]
I opened a PR against your branch with some added tests and a few other small improvements I had in my development queue. As soon as we get that reviewed and in, I'll merge that and a fix I've got for #11, and then I can release a new version.

**Comment by mplanchard** [comment]
Could you verify that the new version uploaded to pypi works as expected?

**Comment by furlongm** [comment]
New version works for me :+1:
